repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      stages: [pre-commit]
      autostage: true
    # Run the formatter.
    - id: ruff-format
      stages: [pre-commit]
      autostage: true
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.8
  hooks:
    - id: uv-lock
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: uv run pytest journal_ai/tests/
      language: system
      pass_filenames: false
      always_run: true