name: Journal AI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      contents: read 
      checks: write 

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --group test

      - name: Run tests
        run: uv run pytest --doctest-modules --junitxml=pytest-results.xml

      - name: Report test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results         
          path: pytest-results.xml
          reporter: java-junit
